nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@arthur/*"

npmScopes:
  arthur:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/54848372/packages/npm/"
    npmAlwaysAuth: true

npmRegistries:
  "https://gitlab.com/api/v4/projects/54848372/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: ${GITLAB_UNIFY_FRONTEND_TOKEN}
